spring:
  application:
    name: dividend

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true
    defer-datasource-initialization: true

  profiles:
    include: jwt


scheduler:
  scrap:
    yahoo: "0 0 0 * * *"